In [3]:
import tensorflow as tf

In [4]:
mnist = tf.keras.datasets.mnist

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()

In [9]:
predictions

array([[ 0.1253799 ,  0.30227724,  0.29280785, -0.21929145, -0.40350637,
        -0.4887227 , -0.369078  ,  0.07501647,  0.90344226,  0.2952883 ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.09864035, 0.11772809, 0.11661854, 0.06988207, 0.0581249 ,
        0.05337688, 0.06016089, 0.09379551, 0.21476464, 0.11690818]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.9303775

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4945 - accuracy: 0.8598
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1554 - accuracy: 0.9533
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1077 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0853 - accuracy: 0.9743
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0762 - accuracy: 0.9766


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0745 - accuracy: 0.9776


[0.07454274594783783, 0.9775999784469604]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.21729165e-08, 3.24797145e-09, 5.24566360e-07, 9.52137543e-06,
        1.05748264e-10, 3.11538372e-07, 1.49484700e-13, 9.99972820e-01,
        1.94043679e-07, 1.64792400e-05],
       [6.99218994e-09, 1.35678611e-05, 9.99981761e-01, 4.17175124e-06,
        4.22965293e-16, 8.36173015e-08, 1.27035031e-08, 1.15262522e-13,
        3.94518111e-07, 3.28648106e-13],
       [6.44696243e-08, 9.98808622e-01, 1.09790068e-04, 8.22908169e-06,
        7.42121920e-05, 8.74323632e-06, 4.10743451e-06, 6.71278569e-04,
        3.14698584e-04, 3.97428522e-07],
       [9.99800622e-01, 8.79506711e-12, 4.34668527e-06, 1.34124063e-08,
        5.31699662e-08, 1.18062335e-05, 4.17101137e-06, 1.09100092e-05,
        2.78248424e-09, 1.68144106e-04],
       [1.05865265e-05, 2.66263234e-09, 4.21378900e-06, 3.77787508e-08,
        9.90523040e-01, 8.13768929e-06, 5.52034771e-06, 2.29091660e-04,
        3.65101073e-06, 9.21572000e-03]], dtype=float32)>